apiVersion: apps/v1
kind: StatefulSet
metadata: 
  name: mariadb-statefulset
  labels: 
    app: mariadb
spec: 
  serviceName: mariadb
  replicas: 1
  selector: 
    matchLabels: 
      app: mariadb
  template:
    metadata: 
      labels: 
        app: mariadb
    spec: 
      containers: 
        - name: mariadb
          image: mariadb
          ports: 
            - containerPort: 3306
          env:
            - name: MARIADB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: my-mariadb-secret
                  key: rootPassword
            - name: MARIADB_DATABASE
              value: wp
            - name: MARIADB_USER
              valueFrom:
                secretKeyRef:
                  name: my-mariadb-secret
                  key: username
            - name: MARIADB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: my-mariadb-secret
                  key: password